export type ChildId = "michal" | "natalka";
export type Weekday = "MO" | "TU" | "WE" | "TH" | "FR";
export type LessonKind =
  | "wf"
  | "edwcz"
  | "angielski"
  | "informatyka"
  | "muzyka"
  | "plastyka"
  | "religia"
  | "zdw"
  | "basen"
  | "extra"
  | "taekwondo"
  | "balet";

export type Lesson = {
  id: string;
  child: string;
  weekday: Weekday;
  start: string;
  end: string;
  title: string;
  kind: LessonKind;
  room?: string;
  teacher?: string;
  location?: string;
  note?: string;
  handwritten?: boolean;
};

export const SCHOOL =
  "SP nr 148 im. Polskich Noblistów, ul. Żabia 20, 30-809 Kraków";

export const SCHOOL_YEAR = {
  label: "2026/2027",
  /** Wtorek 1 września 2026 */
  start: "2026-09-01",
  /** Piątek 25 czerwca 2027 */
  end: "2027-06-25",
};

export const WEEKDAYS: { id: Weekday; label: string; short: string }[] = [
  { id: "MO", label: "Poniedziałek", short: "Pn" },
  { id: "TU", label: "Wtorek", short: "Wt" },
  { id: "WE", label: "Środa", short: "Śr" },
  { id: "TH", label: "Czwartek", short: "Czw" },
  { id: "FR", label: "Piątek", short: "Pi" },
];

export const BELLS = [
  { nr: 0, start: "07:10", end: "07:55" },
  { nr: 1, start: "08:00", end: "08:45" },
  { nr: 2, start: "08:50", end: "09:35" },
  { nr: 3, start: "09:45", end: "10:30" },
  { nr: 4, start: "10:40", end: "11:25" },
  { nr: 5, start: "11:40", end: "12:25" },
  { nr: 6, start: "12:45", end: "13:30" },
  { nr: 7, start: "13:45", end: "14:30" },
  { nr: 8, start: "14:40", end: "15:25" },
  { nr: 9, start: "15:30", end: "16:15" },
  { nr: 10, start: "17:00", end: "17:45" },
];

export const CHILDREN: Record<
  ChildId,
  { name: string; className: string; teacher: string; color: string }
> = {
  michal: {
    name: "Michał",
    className: "3d",
    teacher: "Katarzyna Szynkła",
    color: "#2563eb",
  },
  natalka: {
    name: "Natalka",
    className: "1d",
    teacher: "Urszula Aksamiit-Słupka",
    color: "#c026d3",
  },
};

export const KIND_LABEL: Record<LessonKind, string> = {
  wf: "WF",
  edwcz: "Edukacja wczesnoszkolna",
  angielski: "Język angielski",
  informatyka: "Informatyka",
  muzyka: "Muzyka",
  plastyka: "Plastyka",
  religia: "Religia",
  zdw: "Zajęcia dydaktyczno-wyrównawcze",
  basen: "Basen",
  extra: "Zajęcia dodatkowe",
  taekwondo: "Taekwondo",
  balet: "Balet",
};

export function kindClass(kind: string) {
  return KIND_CLASS[kind as LessonKind] ?? KIND_CLASS.extra;
}

export const KIND_CLASS: Record<LessonKind, string> = {
  wf: "bg-orange-100 text-orange-950 border-orange-200",
  edwcz: "bg-emerald-100 text-emerald-950 border-emerald-200",
  angielski: "bg-sky-100 text-sky-950 border-sky-200",
  informatyka: "bg-slate-100 text-slate-950 border-slate-200",
  muzyka: "bg-violet-100 text-violet-950 border-violet-200",
  plastyka: "bg-amber-100 text-amber-950 border-amber-200",
  religia: "bg-purple-100 text-purple-950 border-purple-200",
  zdw: "bg-teal-100 text-teal-950 border-teal-200",
  basen: "bg-cyan-100 text-cyan-950 border-cyan-200",
  extra: "bg-stone-100 text-stone-950 border-stone-300",
  taekwondo: "bg-red-100 text-red-950 border-red-200",
  balet: "bg-pink-100 text-pink-950 border-pink-200",
};

const MICHAL: Lesson[] = [
  {
    id: "m-mo-wf",
    child: "michal",
    weekday: "MO",
    start: "08:00",
    end: "09:35",
    title: "WF",
    kind: "wf",
    room: "sala A",
    teacher: "B01",
  },
  {
    id: "m-mo-ed1",
    child: "michal",
    weekday: "MO",
    start: "09:45",
    end: "10:30",
    title: "Edukacja wczesnoszkolna",
    kind: "edwcz",
    room: "22A",
    teacher: "Sak",
  },
  {
    id: "m-mo-ed2",
    child: "michal",
    weekday: "MO",
    start: "10:40",
    end: "11:25",
    title: "Edukacja wczesnoszkolna",
    kind: "edwcz",
    room: "13C",
    teacher: "Sak",
  },
  {
    id: "m-mo-ang",
    child: "michal",
    weekday: "MO",
    start: "11:40",
    end: "12:25",
    title: "Język angielski",
    kind: "angielski",
    room: "27C",
    teacher: "KA",
  },
  {
    id: "m-mo-extra",
    child: "michal",
    weekday: "MO",
    start: "12:45",
    end: "13:30",
    title: "Zajęcia dodatkowe",
    kind: "extra",
    room: "22E",
    teacher: "K-ZH",
    handwritten: true,
    note: "Dopisek ręczny na planie (sala 22E, K-ZH).",
  },
  {
    id: "m-mo-basen",
    child: "michal",
    weekday: "MO",
    start: "14:40",
    end: "16:15",
    title: "Basen",
    kind: "basen",
    location: "Basen",
  },
  {
    id: "m-tu-extra1",
    child: "michal",
    weekday: "TU",
    start: "08:00",
    end: "08:45",
    title: "Zajęcia dodatkowe",
    kind: "extra",
    teacher: "GM",
    handwritten: true,
    note: "Dopisek ręczny na planie (BFD / GM).",
  },
  {
    id: "m-tu-ang",
    child: "michal",
    weekday: "TU",
    start: "08:50",
    end: "09:35",
    title: "Język angielski",
    kind: "angielski",
    room: "14C",
    teacher: "KA",
  },
  {
    id: "m-tu-wf",
    child: "michal",
    weekday: "TU",
    start: "09:45",
    end: "10:30",
    title: "WF",
    kind: "wf",
    teacher: "B01",
  },
  {
    id: "m-tu-ed",
    child: "michal",
    weekday: "TU",
    start: "10:40",
    end: "12:25",
    title: "Edukacja wczesnoszkolna",
    kind: "edwcz",
    room: "13C",
    teacher: "Sak",
  },
  {
    id: "m-tu-extra6",
    child: "michal",
    weekday: "TU",
    start: "12:45",
    end: "13:30",
    title: "Zajęcia dodatkowe",
    kind: "extra",
    room: "22B",
    teacher: "D-ZN",
    handwritten: true,
    note: "Dopisek ręczny na planie (sala 22B, D-ZN).",
  },
  {
    id: "m-tu-tkd",
    child: "michal",
    weekday: "TU",
    start: "17:30",
    end: "19:00",
    title: "Taekwondo",
    kind: "taekwondo",
    handwritten: true,
    note: "Trening we wtorki i czwartki, 17:30–19:00.",
  },
  {
    id: "m-we-ang",
    child: "michal",
    weekday: "WE",
    start: "09:45",
    end: "10:30",
    title: "Język angielski",
    kind: "angielski",
    room: "14A",
    teacher: "KA",
  },
  {
    id: "m-we-ed1",
    child: "michal",
    weekday: "WE",
    start: "10:40",
    end: "11:25",
    title: "Edukacja wczesnoszkolna",
    kind: "edwcz",
    room: "14C",
    teacher: "Sak",
  },
  {
    id: "m-we-ed2",
    child: "michal",
    weekday: "WE",
    start: "11:40",
    end: "13:30",
    title: "Edukacja wczesnoszkolna",
    kind: "edwcz",
    room: "13C / 25C",
    teacher: "Sak",
    note: "Lekcja 5: sala 25C, lekcja 6: sala 13C.",
  },
  {
    id: "m-we-zdw",
    child: "michal",
    weekday: "WE",
    start: "13:45",
    end: "14:30",
    title: "Zajęcia dydaktyczno-wyrównawcze",
    kind: "zdw",
    room: "13C",
    teacher: "WW",
  },
  {
    id: "m-th-extra",
    child: "michal",
    weekday: "TH",
    start: "08:00",
    end: "08:45",
    title: "Zajęcia dodatkowe",
    kind: "extra",
    room: "13C",
    note: "Krótki wpis na planie w czwartek na 1. lekcji — odczytany jako zajęcia dodatkowe.",
  },
  {
    id: "m-th-pl",
    child: "michal",
    weekday: "TH",
    start: "08:50",
    end: "09:35",
    title: "Plastyka",
    kind: "plastyka",
    room: "13C",
  },
  {
    id: "m-th-ed",
    child: "michal",
    weekday: "TH",
    start: "09:45",
    end: "12:25",
    title: "Edukacja wczesnoszkolna",
    kind: "edwcz",
    room: "13C / 22A",
    teacher: "Sak",
    note: "Lekcje 3–4 sala 13C, lekcja 5 sala 22A.",
  },
  {
    id: "m-th-rel",
    child: "michal",
    weekday: "TH",
    start: "12:45",
    end: "13:30",
    title: "Religia",
    kind: "religia",
    room: "21A",
    teacher: "JW",
  },
  {
    id: "m-th-tkd",
    child: "michal",
    weekday: "TH",
    start: "17:30",
    end: "19:00",
    title: "Taekwondo",
    kind: "taekwondo",
    handwritten: true,
    note: "Trening we wtorki i czwartki, 17:30–19:00.",
  },
  {
    id: "m-fr-inf",
    child: "michal",
    weekday: "FR",
    start: "08:00",
    end: "08:45",
    title: "Informatyka",
    kind: "informatyka",
    room: "14C",
  },
  {
    id: "m-fr-ed",
    child: "michal",
    weekday: "FR",
    start: "08:50",
    end: "10:30",
    title: "Edukacja wczesnoszkolna",
    kind: "edwcz",
    room: "13C",
    teacher: "Sak",
  },
  {
    id: "m-fr-muz",
    child: "michal",
    weekday: "FR",
    start: "10:40",
    end: "11:25",
    title: "Muzyka",
    kind: "muzyka",
    room: "13C",
  },
  {
    id: "m-fr-ang",
    child: "michal",
    weekday: "FR",
    start: "11:40",
    end: "12:25",
    title: "Język angielski",
    kind: "angielski",
    room: "24C",
    teacher: "KA",
  },
];

const NATALKA: Lesson[] = [
  {
    id: "n-mo-ang",
    child: "natalka",
    weekday: "MO",
    start: "09:45",
    end: "10:30",
    title: "Język angielski",
    kind: "angielski",
    room: "18A",
    teacher: "KN",
  },
  {
    id: "n-mo-wf",
    child: "natalka",
    weekday: "MO",
    start: "10:40",
    end: "11:25",
    title: "WF",
    kind: "wf",
    room: "sala A",
    teacher: "A-SU",
  },
  {
    id: "n-mo-ed",
    child: "natalka",
    weekday: "MO",
    start: "11:40",
    end: "15:25",
    title: "Edukacja wczesnoszkolna",
    kind: "edwcz",
    room: "15C",
    teacher: "A-SU",
  },
  {
    id: "n-tu-wf",
    child: "natalka",
    weekday: "TU",
    start: "10:40",
    end: "11:25",
    title: "WF",
    kind: "wf",
    room: "SG2",
    teacher: "A-SU",
  },
  {
    id: "n-tu-ang",
    child: "natalka",
    weekday: "TU",
    start: "11:40",
    end: "12:25",
    title: "Język angielski",
    kind: "angielski",
    room: "15C",
    teacher: "KN",
  },
  {
    id: "n-tu-inf",
    child: "natalka",
    weekday: "TU",
    start: "12:45",
    end: "13:30",
    title: "Informatyka",
    kind: "informatyka",
    room: "21C",
    teacher: "A-SU",
  },
  {
    id: "n-tu-basen",
    child: "natalka",
    weekday: "TU",
    start: "13:45",
    end: "15:25",
    title: "Basen",
    kind: "basen",
    location: "Basen",
  },
  {
    id: "n-tu-balet",
    child: "natalka",
    weekday: "TU",
    start: "17:40",
    end: "18:50",
    title: "Balet",
    kind: "balet",
    handwritten: true,
    note: "Dopisek ręczny: 17:40–18:50.",
  },
  {
    id: "n-we-ed1",
    child: "natalka",
    weekday: "WE",
    start: "08:50",
    end: "09:35",
    title: "Edukacja wczesnoszkolna",
    kind: "edwcz",
    room: "14C",
    teacher: "A-SU",
  },
  {
    id: "n-we-wf",
    child: "natalka",
    weekday: "WE",
    start: "09:45",
    end: "10:30",
    title: "WF",
    kind: "wf",
    room: "sala A",
    teacher: "A-SU",
  },
  {
    id: "n-we-ed2",
    child: "natalka",
    weekday: "WE",
    start: "10:40",
    end: "14:30",
    title: "Edukacja wczesnoszkolna",
    kind: "edwcz",
    room: "15C",
    teacher: "A-SU",
  },
  {
    id: "n-th-muz",
    child: "natalka",
    weekday: "TH",
    start: "10:40",
    end: "11:25",
    title: "Muzyka",
    kind: "muzyka",
    room: "15C",
    teacher: "A-SU",
  },
  {
    id: "n-th-ang",
    child: "natalka",
    weekday: "TH",
    start: "11:40",
    end: "12:25",
    title: "Język angielski",
    kind: "angielski",
    room: "15C",
    teacher: "KN",
  },
  {
    id: "n-th-ed",
    child: "natalka",
    weekday: "TH",
    start: "12:45",
    end: "14:30",
    title: "Edukacja wczesnoszkolna",
    kind: "edwcz",
    room: "15C",
    teacher: "A-SU",
  },
  {
    id: "n-th-zdw",
    child: "natalka",
    weekday: "TH",
    start: "14:40",
    end: "15:25",
    title: "Zajęcia dydaktyczno-wyrównawcze",
    kind: "zdw",
    room: "15C",
    teacher: "WW",
  },
  {
    id: "n-th-balet",
    child: "natalka",
    weekday: "TH",
    start: "16:05",
    end: "17:10",
    title: "Balet",
    kind: "balet",
    handwritten: true,
    note: "Dopisek ręczny: 16:05–17:10.",
  },
  {
    id: "n-fr-ang",
    child: "natalka",
    weekday: "FR",
    start: "08:00",
    end: "08:45",
    title: "Język angielski",
    kind: "angielski",
    room: "15C",
    teacher: "KN",
  },
  {
    id: "n-fr-ed",
    child: "natalka",
    weekday: "FR",
    start: "08:50",
    end: "10:30",
    title: "Edukacja wczesnoszkolna",
    kind: "edwcz",
    room: "15C",
    teacher: "A-SU",
  },
  {
    id: "n-fr-pl",
    child: "natalka",
    weekday: "FR",
    start: "10:40",
    end: "11:25",
    title: "Plastyka",
    kind: "plastyka",
    room: "15C",
    teacher: "A-SU",
  },
  {
    id: "n-fr-rel",
    child: "natalka",
    weekday: "FR",
    start: "11:40",
    end: "12:25",
    title: "Religia",
    kind: "religia",
    room: "15C",
    teacher: "O-SsW",
  },
];

export const LESSONS: Lesson[] = [...MICHAL, ...NATALKA];

export function lessonsFor(child: ChildId | "all"): Lesson[] {
  if (child === "all") return LESSONS;
  return LESSONS.filter((l) => l.child === child);
}

export const FIRST_DATES: Record<Weekday, string> = {
  MO: "2026-09-07",
  TU: "2026-09-01",
  WE: "2026-09-02",
  TH: "2026-09-03",
  FR: "2026-09-04",
};
